# vim ft=yaml
# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

dist: xenial  # Ubuntu 16.04

install:
  - sudo apt-get install libboost-all-dev libtbb-dev

script:
  - ./build.sh
  - ./build/oak/apps/local_classification/trainer/oak2_local_class_trainer --help

#after_success:
#  - ./build/oak2/apps/local_classification/trainer/oak2_local_class_trainer --help

notifications:
  email: false
